notify = [ "C:\\Users\\21452\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\1b23c930bdf84ed6\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]

approval_policy = "never"
sandbox_mode = "danger-full-access"
personality = "pragmatic"

model_provider = "chatgpt_http"

[model_providers.chatgpt_http]
name = "ChatGPT HTTP"
base_url = "https://chatgpt.com/backend-api/codex"
wire_api = "responses"
requires_openai_auth = true
supports_websockets = false

[marketplaces.openai-bundled]
last_updated = "2026-07-02T17:22:59Z"
source_type = "local"
source = '\\?\C:\Users\21452\.codex\.tmp\bundled-marketplaces\openai-bundled'

[plugins."browser@openai-bundled"]
enabled = true

[features]
js_repl = true

[mcp_servers.node_repl]
args = []
command = 'C:\Users\21452\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node_repl.exe'
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\21452\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\21452\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\21452\.codex'
CODEX_HOME = 'C:\Users\21452\.codex'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "566be6ef352eb3de899adc56a9cd7b5e46c8f65b00e56b5630dd7a580e10cbea,cb79053fda6deb0f3b5d6f0d90d4257305ebdbd1e378a12e8fbc5bde782eb59b"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.81905"
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-e0269984-9f62-47fe-a498-0304762479dd'
CODEX_CLI_PATH = 'C:\Users\21452\AppData\Local\OpenAI\Codex\bin\ea1c60319a1dcb19\codex.exe'

[mcp_servers.burp]
command = 'D:\Users\21452\Desktop\tools\BurpSuite V2026.4.2\jre\bin\java.exe'
args = [
  "-jar",
  'C:\Users\21452\mcp-server\libs\mcp-proxy-all.jar',
  "--sse-url",
  "http://127.0.0.1:9876"
]
startup_timeout_sec = 120
tool_timeout_sec = 120
enabled = true

[mcp_servers.burp.tools.get_organizer_items_regex]
approval_mode = "approve"

[mcp_servers.burp.tools.send_http1_request]
approval_mode = "approve"

[mcp_servers.burp.tools.send_http2_request]
approval_mode = "approve"

[mcp_servers.playwright]
command = 'C:\Windows\System32\cmd.exe'
args = ["/c", "npx", "-y", "@playwright/mcp@latest", "--browser=chrome", "--proxy-server=http://127.0.0.1:8080", "--ignore-https-errors", "--isolated"]
enabled = true
startup_timeout_sec = 120
tool_timeout_sec = 120

[desktop]
conversationDetailMode = "STEPS_PROSE"
sansFontSize = 14
codeFontSize = 13
ambient-suggestions-enabled = false
appearanceTheme = "dark"

model_instructions_file = "./gpt5.5-unrestricted.md"

[tui.model_availability_nux]
"gpt-5.5" = 3
