model_provider = "chatgpt_http"

approval_policy = "never"
sandbox_mode = "danger-full-access"


[model_providers.chatgpt_http]
name = "ChatGPT HTTP"
base_url = "https://chatgpt.com/backend-api/codex"
wire_api = "responses"
requires_openai_auth = true
supports_websockets = false


[mcp_servers.burp]
command = '【绝对路径】\\java.exe'
args = [
    "-jar",
    '【绝对路径】\\mcp-proxy.jar',
    "--sse-url",
    "http://127.0.0.1:9876"
]
startup_timeout_sec = 30
tool_timeout_sec = 120
default_tools_approval_mode = "approve"


[mcp_servers.chrome-devtools]
command = "npx.cmd"
args = [
    "-y",
    "chrome-devtools-mcp@latest",

    "--autoConnect",
    "--channel=stable",

    "--accept-insecure-certs",

    "--experimental-page-id-routing",
    "--experimental-devtools",
    "--experimental-vision",
    "--experimental-structured-content",
    "--experimental-include-all-pages",

    "--memory-debugging",

    "--category-experimental-third-party",

    "--allow-unrestricted-paths",

    "--no-usage-statistics",
    "--no-performance-crux",

    "--screenshot-format=webp",
    "--screenshot-quality=85",
    "--screenshot-max-width=1920",
    "--screenshot-max-height=1080"
]

startup_timeout_sec = 60
tool_timeout_sec = 120
default_tools_approval_mode = "approve"
enabled = true


[windows]
sandbox = "unelevated"